name: MacOS CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        brew install conan@1
        export PATH="/usr/local/opt/conan@1/bin:$PATH"
        conan user
    - name: prepare
      run: |
        export PATH="/usr/local/opt/conan@1/bin:$PATH"
        make prepare
        make setup_conan
    - name: configure
      run: |
        export PATH="/usr/local/opt/conan@1/bin:$PATH"
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
    - name: building
      run: |
        export PATH="/usr/local/opt/conan@1/bin:$PATH"
        cmake --build build --config Debug --target calc_console -j4
